Update to use go1.18 and generate versioned images
m-lab/gcp-config pull request #63
Opened 2022-08-31 22:27 UTC by stephen-soltesz

This change completes the update to golang:1.18 for all Dockerfiles in this repo.

All generated images are now versioned. Previously untagged images will continue to work, but dependencies (e.g. siteinfo) should be migrated to the latest tagged version for consistency.

Part of:
* https://github.com/m-lab/dev-tracker/issues/735

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/m-lab/gcp-config/63)

2022-08-31 22:30 UTC, SaiedKazemi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAq0nVC5SaoibgM6vHW:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @nkinkade)



<!-- Sent from Reviewable.io -->

2022-08-31 22:37 UTC, stephen-soltesz commented
@nkinkade PTAL also when you have a moment. This is relevant to your regular work.

2022-08-31 22:50 UTC, nkinkade requested changes
What is the rationale for versioning the container images this repo creates using the underlying Go version in the image? What happens if want to update the Dockerfile to do something different (e.g., install some other packages), which changes the resulting image. What image version do we use then?

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAq1R92CDkJxTUanQtg:blvmzu)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`Dockerfile.epoxy-images` line 32 at r1](https://reviewable.io/reviews/m-lab/gcp-config/63#-NAq3_DFCqwFIfS7p-G2:-NAq3_DFCqwFIfS7p-G3:bmqjmdl) ([raw file](https://github.com/m-lab/gcp-config/blob/823204e3917cc39613828c6d473e37f43577e26a/Dockerfile.epoxy-images#L32)):*
> ```
> # -s    Omit the symbol table and debug information.
> #RUN go install github.com/m-lab/epoxy/cmd/epoxy_client@latest
> RUN CGO_ENABLED=0 GO111MODULE=auto go install -ldflags '-w -s' github.com/m-lab/epoxy/cmd/epoxy_client@latest
> ```

Out of curiosity why `GO111MODULE=auto`?

Also, please remove the commented out RUN command.


<!-- Sent from Reviewable.io -->

2022-08-31 22:57 UTC, stephen-soltesz reviewed
I think any version would do. Using the Go version was a convenience and I believe the original reason for https://github.com/m-lab/gcp-config/pull/58 was because of a mismatch between the included Go version and a user in another repo. Also, this follows a pattern of the golang packages or other docker images that embed the relevant version into the tag. But, if the go version doesn't make sense for some of these (e.g. maybe Dockerfile.epoxy-images shouldn't be so tightly coupled to the go version), I'm open to alternate schemes. The Go version was just obvious to me.. expoxy-images for example could be pinned to a recent release of the epoxy repo so the epoxy_client is versioned for example. What do you think? What would work better here?

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAq68Dz3c5iNsiCCQL9:belswzp)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained (waiting on @nkinkade)

___
*[`Dockerfile.epoxy-images` line 32 at r1](https://reviewable.io/reviews/m-lab/gcp-config/63#-NAq3_DFCqwFIfS7p-G2:-NAq674f2hAZCGIQvF4B:b-896fix) ([raw file](https://github.com/m-lab/gcp-config/blob/823204e3917cc39613828c6d473e37f43577e26a/Dockerfile.epoxy-images#L32)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Out of curiosity why `GO111MODULE=auto`?

Also, please remove the commented out RUN command.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-31 23:03 UTC, nkinkade reviewed
How about the version of the gcp-config repository? My main concern was the case where we modify the Dockerfile, changing the underlying image in some fundamental way, and then wanting to reflect that in a new image tag, but it not making much sense. For example, if we later change the file "Dockerfile.siteinfo", and we wanted that reflected in a new image tag, would we tag the image was something like `1.18.1`, or `1.18.0-mlab1`, etc.? Or, would we just leave the tag the same such that the underlying image changes but the tag remains the same (which sort of defeats the purpose of tagging and not just using "latest"). Am I overthinking this?

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAq7Tpv12R69MIPvMEA:btvgacw)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-01 14:58 UTC, stephen-soltesz reviewed
Your questions are good. Part of what I've done is arbitrary (e.g. choosing the golang version as the tag). I may not be great answers. But, I want to find an approach that makes sense to us.

If we used the gcp-config repo version, it could be awkward using a label before a tag existed or tagging and then applying the label.

Many of these base images apply updates to a short named tag. e.g. golang:1.18.4 and golang:1.18.5 exist, but golang:1.18 is updated with whatever the latest version is at the time. Just to say that under some circumstances it's okay to update an image tag. This is better than "latest" b/c it still pins (what should be) a backward compatible version for all users. And, (for example) users still using golang:1.17 are not disturbed by changes to golang:1.18. And, users of golang:1.18 are not disturbed when 1.19 is available.

Rather than golang's version, is there a tag that's more representative of the epoxy-images image?

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAtKWnGA4jsUfWpdug7:bau1635)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-01 15:54 UTC, nkinkade reviewed
Ah, good point that it would be awkward to add a repo release tag to the container images _before_ actually tagging the repo. It could work, but it requires planning and would be somewhat backward.

How about an arbitrary tag as a starting point like `1.0.0`, since this the first time we are tagging these images. The next time changes are introduced to one of the Docker files, the person doing the modifications just updates the tag for that image accordingly?

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAtjxDLCQbLuQ0BEUhp:b-sdmt48)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-01 16:51 UTC, stephen-soltesz reviewed
Okay. I've used 1.0 for all images other than the explicitly golang version (which preserves the golang version in the tag).

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAtxck_7URAI-O4B2Iq:bh5oh85)* status: :shipit: complete! 1 change requests, 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-01 17:16 UTC, nkinkade approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/gcp-config/63#-:-NAu2OwjBU0ad3sv7beL:bnfp4nl)* status: :shipit: complete! 2 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-09-01 18:01 UTC, stephen-soltesz commented
Thank you!

2022-09-01 18:02 UTC, merged